version: '2'


ejabberd:
  image: ejabberd/ecs
  ports:
    - 5222:5222
    - 5269:5269
    - 5280:5280
   volumes:
     - ./conf/ejabberd.yml:/home/ejabberd/conf/ejabberd.yml
     - ./database:/home/ejabberd/database
